### ISSUE TITLE
Bad place name in Ukraine

### ISSUE THREAD

**Issue by dianashk** [whosonfirst/whosonfirst-data#292] opened 2016-05-19 19:23 UTC
This record [102088769](https://whosonfirst.mapzen.com/spelunker/id/102088769/#9/50.4246/30.4082) has the name is set to `ÐÐ¸ÑÐ²Ð¾-Ð¡Ð²ÑÑÐ¾ÑÐ¸Ð½ÑÑÐºÐ¸Ð¹` which seems unlikely. :)

**Comment by stepps00** [comment] 2016-05-19 22:24
Related to https://github.com/whosonfirst/whosonfirst-data/issues/244

**Comment by thisisaaronland** [comment] 2016-05-27 19:15
This is a dupe of issue #244

**Closed by thisisaaronland** 2016-05-27 19:15 UTC
