### ISSUE TITLE
Clean up Census (balance) names

### ISSUE THREAD

**Issue by riordan** [whosonfirst/whosonfirst-data#193] opened 2016-01-22 21:44 UTC
@martinburch from the Wall Street Journal flagged an issue (pelias/pelias#237) with several locality names in WoF/Quattroshapes where the name of the city ends in `(balance)`:

>In both OSM and Quattroshapes, some localities end in "balance" as in `Athens-Clarke County Unified Government (balance)`

https://search.mapzen.com/v1/reverse?api_key=xxxxxxxxx&point.lat=33.94806&point.lon=-83.3275&sources=osm

([Example link](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=33.94806&point.lon=-83.3275&sources=osm)]

> This looks like an artifact of Census-derived data. There are only a handful of these in the U.S. Can this be cleaned up somehow?

**Comment by orangejulius** [comment] 2016-01-22 21:49
Also see https://github.com/pelias/pelias/issues/137

**Comment by nvkelso** [comment] 2016-01-23 03:57
Yeah, those are just weird Census artifacts and will be cleaned up.

**Comment by dianashk** [comment] 2016-04-18 20:14
Also found in [Indianapolis city]( https://whosonfirst.mapzen.com/spelunker/id/85942569/#10/39.7799/-86.1328)
`Indianapolis city (balance)`

**Comment by nvkelso** [comment] 2016-04-18 20:35
Please propose a PR with name fixes to review. Stephen Epps can do a quick scan of that next week.

But the " (balance)" root cause from Census should be split off and dealt with as a separate issue: should the various parts of Indianapolis be merged into one record, for instance, with multiple county parents?

**Comment by stepps00** [comment] 2016-06-14 21:55
Fixed this issue elsewhere.

**Closed** 2016-06-14 21:56 UTC
