### ISSUE TITLE
Concordances for Wikidata IDs

### ISSUE THREAD

**Issue by riordan** [whosonfirst/whosonfirst-data#165] opened 2015-11-12 21:29 UTC
Many WoF places have presences in the Wikipedia ecosystem, which means they have ID's in Wikidata.

Wikidata's useful in that it provides its own concordances we can pull from (Geonames + Freebase) and frequently updated population statistics.

Lets create a concordance field to store Wikidata ID's. This can be bootstrapped with matching existing concordances with Geonames ID's (~641k of them).

**Comment by nvkelso** [comment] 2015-11-12 21:50
Is this a duplicate of https://github.com/whosonfirst/whosonfirst-data/issues/113?

**Comment by riordan** [comment] 2015-11-12 22:06
Possibly. I'll leave it to you, @nvkelso and @thisisaaronland to decide.

Wikidata is different from Wikipedia in that its a separate database with separate IDs and has entries for stuff not in English wikipedia. It's designed to be manifested as a database proper vs. human readable articles. It's where the facts that power many wikipedia infoboxes are stored (among other things), making them standalone database fields rather than freely editable text entry stored in markup on the page.

Take, for example, the entry for Bruzolo, Italy.

It's https://www.wikidata.org/wiki/Q9101 in Wikidata. There are 35 separate Wikipedia pages for Bruzolo in different languages, but they all draw on the Wikidata entry for the population. If it changes here, it changes on all those pages (and any other place that relies on it).

So while it starts as just another concordance, over time, it could grow into a nice way to start managing data updates for many of these places. But the ID is fundamentally different from the English Wikipedia page and would require a crosswalk from wikipedia ID -> wikidata ID.

**Comment by nvkelso** [comment] 2015-11-12 22:30
Cool, sounds different enough to track it as a separate task.

**Comment by thisisaaronland** [comment] 2016-01-07 21:07
We did this. Or at least we did the first pass...

**Closed by thisisaaronland** 2016-01-07 21:07 UTC
Labels: question
